In [90]:
import numpy as np
import pandas as pd

### Example with a custom hight and weight dataset

In [91]:
data = pd.read_csv('altura_peso_dataset.csv')
data

Altura (cm)  Peso (kg)
0           188      80.60
1           178      78.10
2           164      63.80
3           192      87.40
4           157      67.65
..          ...        ...
95          190      91.50
96          178      86.10
97          164      64.80
98          194      78.30
99          150      61.50

[100 rows x 2 columns]

In [92]:
X = data.iloc[:,0].values
y = data.iloc[:,1].values

In [93]:
X

array([188, 178, 164, 192, 157, 170, 188, 168, 172, 160, 160, 173, 185,
       189, 173, 152, 171, 151, 173, 193, 179, 187, 151, 170, 182, 161,
       171, 193, 174, 198, 176, 191, 177, 165, 164, 196, 200, 193, 152,
       186, 200, 156, 170, 158, 188, 167, 153, 174, 163, 199, 158, 175,
       151, 169, 177, 196, 156, 193, 157, 196, 184, 163, 166, 185, 199,
       189, 153, 151, 155, 191, 153, 178, 167, 175, 193, 183, 159, 185,
       163, 180, 197, 164, 157, 163, 172, 189, 170, 165, 194, 167, 196,
       173, 175, 174, 194, 190, 178, 164, 194, 150], dtype=int64)

In [94]:
y

array([80.6 , 78.1 , 63.8 , 87.4 , 67.65, 76.5 , 92.6 , 81.6 , 74.4 ,
       64.  , 64.  , 67.85, 77.25, 84.05, 73.85, 66.4 , 72.95, 65.95,
       74.85, 87.85, 71.55, 74.15, 72.95, 70.5 , 73.9 , 73.45, 73.95,
       78.85, 68.3 , 81.1 , 73.2 , 89.95, 82.65, 66.25, 63.8 , 82.2 ,
       93.  , 82.85, 66.4 , 87.7 , 94.  , 69.2 , 78.5 , 79.1 , 80.6 ,
       81.15, 77.85, 71.3 , 67.35, 85.55, 73.1 , 82.75, 67.95, 69.05,
       81.65, 84.2 , 78.2 , 77.85, 69.65, 90.2 , 92.8 , 68.35, 75.7 ,
       84.25, 98.55, 85.05, 64.85, 57.95, 59.75, 94.95, 70.85, 78.1 ,
       67.15, 74.75, 81.85, 79.35, 69.55, 77.25, 63.35, 89.  , 87.65,
       74.8 , 74.65, 71.35, 86.4 , 91.05, 82.5 , 83.25, 88.3 , 71.15,
       79.2 , 69.85, 84.75, 72.3 , 93.3 , 91.5 , 86.1 , 64.8 , 78.3 ,
       61.5 ])

In [95]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler((-1,1))
X_scaled = scaler.fit_transform(X.reshape(-1, 1))

In [96]:
X_scaled

array([[ 0.52],
       [ 0.12],
       [-0.44],
       [ 0.68],
       [-0.72],
       [-0.2 ],
       [ 0.52],
       [-0.28],
       [-0.12],
       [-0.6 ],
       [-0.6 ],
       [-0.08],
       [ 0.4 ],
       [ 0.56],
       [-0.08],
       [-0.92],
       [-0.16],
       [-0.96],
       [-0.08],
       [ 0.72],
       [ 0.16],
       [ 0.48],
       [-0.96],
       [-0.2 ],
       [ 0.28],
       [-0.56],
       [-0.16],
       [ 0.72],
       [-0.04],
       [ 0.92],
       [ 0.04],
       [ 0.64],
       [ 0.08],
       [-0.4 ],
       [-0.44],
       [ 0.84],
       [ 1.  ],
       [ 0.72],
       [-0.92],
       [ 0.44],
       [ 1.  ],
       [-0.76],
       [-0.2 ],
       [-0.68],
       [ 0.52],
       [-0.32],
       [-0.88],
       [-0.04],
       [-0.48],
       [ 0.96],
       [-0.68],
       [ 0.  ],
       [-0.96],
       [-0.24],
       [ 0.08],
       [ 0.84],
       [-0.76],
       [ 0.72],
       [-0.72],
       [ 0.84],
       [ 0.36],
       [-0.48],
       [

In [97]:
# Hyperbolic Tangent Activation Function
# To avaoid numeric overflow, use np.tanh
def tanh(x, derivate=False):
    if derivate:
        y = tanh(x)
        return 1 - y**2
    return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

In [98]:
D = X_scaled.shape[1]
w = 2*np.random.random(size=D)-1
b = 2*np.random.random()-1
lr = 1e-2
epochs = 2000

In [99]:
for epoch in range(epochs):
    cost = 0
    for x_n, y_n in zip(X_scaled, y):
        y_pred = np.dot(x_n, w) + b
        y_pred = np.tanh(y_pred)
        error = y_n - y_pred
        w = w + lr*np.dot(error, x_n)
        b = b + error*lr
        cost += error**2

    if epoch%100 == 0:
        print(f'Epoch: {epoch} Cost: {cost}')

print(f'W: {w}')
print(f'B: {b}')
print(f'LR: {lr}')

Epoch: 0 Cost: 588165.5579949532
Epoch: 100 Cost: 587894.8225
Epoch: 200 Cost: 587894.8225
Epoch: 300 Cost: 587894.8225
Epoch: 400 Cost: 587894.8225
Epoch: 500 Cost: 587894.8225
Epoch: 600 Cost: 587894.8225
Epoch: 700 Cost: 587894.8225
Epoch: 800 Cost: 587894.8225
Epoch: 900 Cost: 587894.8225
Epoch: 1000 Cost: 587894.8225
Epoch: 1100 Cost: 587894.8225
Epoch: 1200 Cost: 587894.8225
Epoch: 1300 Cost: 587894.8225
Epoch: 1400 Cost: 587894.8225
Epoch: 1500 Cost: 587894.8225
Epoch: 1600 Cost: 587894.8225
Epoch: 1700 Cost: 587894.8225
Epoch: 1800 Cost: 587894.8225
Epoch: 1900 Cost: 587894.8225
W: [6810.26276791]
B: 152272.98004643212
LR: 0.01
